/*
 * This source file was generated by the Gradle 'init' task
 */


package lab5;

import java.util.Arrays;

import lab5.communication.Handler;

import lab5.io.console.*;


public class App {
    public static void main(String[] args) {
         try (Console console = new StandartConsole()) {
            new Handler(console).run();
        } catch (Exception e) {
            System.err.println("[ERROR]" + Arrays.toString(e.getStackTrace()));
        }

       // FileManager fileManager = new CSVFileManager();
        //fileManager.readFile();
    }
}
